spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_dev
    username: erp_user
    password: dev_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.sumeet.erp: DEBUG